name: Bug report
description: Use this template to report a bug in the mod. Provide detailed information to help us identify and resolve the issue.
title: "[BUG]: "
labels: ["bug"]
projects: FartSolutions/20

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug and for completing this form.

  - type: input
    id: contact
    attributes:
      label: Contact details
      description: |
        How can we get in touch with you if we need more info?
      placeholder: |
        ex. email@example.com or Discord name (easiest via our Discord server)
    validations:
      required: true

  - type: checkboxes
    id: no-existing-issues
    attributes:
      label: Is there an existing issue for this?
      description: |
        Please search to see if an issue already exists for the bug you encountered.
      options:
      - label: I have searched the existing issues
    validations:
      required: true

  - type: dropdown
    id: minecraft-version
    attributes:
      label: Minecraft version
      description: |
        Which minecraft version do you used?
      options:
        - 1.12.2
    validations:
      required: true

  - type: input
    id: forge-version
    attributes:
      label: Forge version
      description: |
        Which forge version do you used?
      placeholder: |
        Example: 14.23.5.2860
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Location
      description: |
        Specify the file and the function, method, or structure where the bug occurs.
      placeholder: |
        Example: path/core.java function/method/struct/... do_something()
    validations:
      required: true

  - type: textarea
    id: issue-description
    attributes:
      label: Issue description
      description: |
        Describe the bug in detail. Include steps to reproduce, excepted outcomes, and actual outcomes.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
      placeholder: |
        Detailed description of the issue...
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
