blank_issues_enabled: false

contact_links:
  - name: Github Community Support
    url: https://github.com/orgs/FartSolutions/discussions/new/choose
    about: Please ask and answer questions here.
  - name: Discord community
    url: https://discord.com/invite/QUrzDAgm58
    about: Please also ask and answer questions here.
